<a href="https://colab.research.google.com/github/arunjaiswal1411/arunjaiswal1411/blob/main/Final_Binding_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

In [ ]:
#Import dataset
#creating a variable
dataset = pd.read_csv('Final_Binding.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[['WP004583577.1' 'DLNC_ZINC03841756' -8.6 1.55]
 ['WP004584226.1' 'DLNC_ZINC04235909' -7.5 4.437]
 ['WP010956218.1' 'DLNC_ZINC03840461' -9.3 nan]
 ['WP004583577.1' 'DLNC_ZINC03841756' nan 1.55]
 ['WP004584226.1' 'DLNC_ZINC04235909' -7.7 4.437]
 ['WP010956218.1' 'DLNC_ZINC03840461' -8.9 1.8259999999999998]]
[2 2 3 3 3 5]


In [ ]:
#Taking care of missing data
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:4])
x[:, 2:4] = imputer.transform(x[:, 2:4])
print(x)

[['WP004583577.1' 'DLNC_ZINC03841756' -8.6 1.55]
 ['WP004584226.1' 'DLNC_ZINC04235909' -7.5 4.437]
 ['WP010956218.1' 'DLNC_ZINC03840461' -9.3 2.7600000000000002]
 ['WP004583577.1' 'DLNC_ZINC03841756' -8.4 1.55]
 ['WP004584226.1' 'DLNC_ZINC04235909' -7.7 4.437]
 ['WP010956218.1' 'DLNC_ZINC03840461' -8.9 1.8259999999999998]]


In [ ]:
#Encoding categorical data
#Encoding the Independent Variable
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 'DLNC_ZINC03841756' -8.6 1.55]
 [0.0 1.0 0.0 'DLNC_ZINC04235909' -7.5 4.437]
 [0.0 0.0 1.0 'DLNC_ZINC03840461' -9.3 2.7600000000000002]
 [1.0 0.0 0.0 'DLNC_ZINC03841756' -8.4 1.55]
 [0.0 1.0 0.0 'DLNC_ZINC04235909' -7.7 4.437]
 [0.0 0.0 1.0 'DLNC_ZINC03840461' -8.9 1.8259999999999998]]


In [ ]:
#Encoding categorical data
#Encoding the Dependent data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 0 1 1 1 2]


In [ ]:
#Splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 'DLNC_ZINC04235909' -7.7 4.437]
 [1.0 0.0 0.0 'DLNC_ZINC03841756' -8.6 1.55]
 [1.0 0.0 0.0 'DLNC_ZINC03841756' -8.4 1.55]
 [0.0 0.0 1.0 'DLNC_ZINC03840461' -8.9 1.8259999999999998]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 'DLNC_ZINC03840461' -9.3 2.7600000000000002]
 [0.0 1.0 0.0 'DLNC_ZINC04235909' -7.5 4.437]]


In [ ]:
print(y_train)

[1 0 1 2]


In [ ]:
print(y_test)

[1 0]


In [ ]:
#feature scaling
#Implementation of Feature scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

In [ ]:
print(x_train)

[[0.0 1.0 0.0 'DLNC_ZINC04235909' 1.5851878478024344 1.7245928387269933]
 [1.0 0.0 0.0 'DLNC_ZINC03841756' -0.4529108136578367 -0.6505530290868787]
 [1.0 0.0 0.0 'DLNC_ZINC03841756' 0.0 -0.6505530290868787]
 [0.0 0.0 1.0 'DLNC_ZINC03840461' -1.1322770341445958 -0.4234867805532354]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 'DLNC_ZINC03840461' -2.038098661460273 0.34491856774539886]
 [0.0 1.0 0.0 'DLNC_ZINC04235909' 2.038098661460273 1.7245928387269933]]
